{% set name = "membrane-curvature" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/membrane_curvature-{{ version }}.tar.gz
  sha256: 6b5775e53a69689d222b373353909bcd2625ef4a1090a1b5c34ca14943d8516b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0
    - mdanalysis >=2.0.0

test:
  imports:
    - membrane_curvature
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - membrane_curvature/tests

about:
  home: https://github.com/MDAnalysis/membrane-curvature
  summary: MDAnalysis tool to calculate membrane curvature from MD simulations.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://membrane-curvature.readthedocs.io/
  dev_url: https://github.com/MDAnalysis/membrane-curvature

extra:
  recipe-maintainers:
    - ojeda-e
